name: Deploy Iframe List

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run PHP script to generate iframe list
        run: php generate-iframe-list.php

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './index.html'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
